
services:
  postgres:
    image: postgres:alpine
    container_name: postgres-db
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PGDATA=/data/db/pgdata
    ports:
      - 5432:5432
    volumes:
      - ./postgres/pgdata/:/data/db
    restart: on-failure

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-0.1.0
    command: sh -c "gunicorn --bind 0.0.0.0:8000 --workers=4 core.wsgi --reload"
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - .:/code
    depends_on:
      - postgres
    restart: on-failure
